# Secret Manager: the Google OAuth client secret.
#
# Terraform creates the secret CONTAINER only — the value is added
# out-of-band (`just secret-set`) so it never touches Terraform state.
# State files are not a safe place for credentials.

resource "google_secret_manager_secret" "oauth_client_secret" {
  secret_id = "${var.service_name}-google-oauth-client-secret"

  replication {
    auto {}
  }

  depends_on = [google_project_service.apis]
}

# Only the service's dedicated service account may read it.
resource "google_secret_manager_secret_iam_member" "service_can_read" {
  secret_id = google_secret_manager_secret.oauth_client_secret.secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.run_service.email}"
}

# MRTR requestState HMAC secret (SEP-2322). requestState blobs transit the
# client, so the spec requires integrity protection; with session affinity
# plus max_instances > 1 (and instance recycling), the HMAC key must be
# SHARED — a per-process random key would invalidate a retry that lands on
# a different instance. The value is generated by the deploy workflow
# (random bytes, added only if no version exists yet) so it never appears
# in Terraform state either.
resource "google_secret_manager_secret" "request_state_secret" {
  secret_id = "${var.service_name}-request-state-secret"

  replication {
    auto {}
  }

  depends_on = [google_project_service.apis]
}

resource "google_secret_manager_secret_iam_member" "request_state_read" {
  secret_id = google_secret_manager_secret.request_state_secret.secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.run_service.email}"
}

# Stable FastMCP OAuth proxy keys. The deploy workflow seeds both values once;
# Terraform manages only their containers and IAM policies. Keeping signing
# and at-rest encryption keys separate avoids key reuse across cryptographic
# purposes.
resource "google_secret_manager_secret" "oauth_jwt_signing_key" {
  secret_id = "${var.service_name}-oauth-jwt-signing-key"

  replication {
    auto {}
  }

  depends_on = [google_project_service.apis]
}

resource "google_secret_manager_secret_iam_member" "oauth_jwt_signing_key_read" {
  secret_id = google_secret_manager_secret.oauth_jwt_signing_key.secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.run_service.email}"
}

resource "google_secret_manager_secret" "oauth_storage_encryption_key" {
  secret_id = "${var.service_name}-oauth-storage-encryption-key"

  replication {
    auto {}
  }

  depends_on = [google_project_service.apis]
}

resource "google_secret_manager_secret_iam_member" "oauth_storage_encryption_key_read" {
  secret_id = google_secret_manager_secret.oauth_storage_encryption_key.secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.run_service.email}"
}
